export { default as ChromeIcon } from './CHROME_ICON.svg'
export { default as DiscordIcon } from './DISCORD_ICON.svg'
export { default as GitHubIcon } from './GITHUB_ICON.svg'
export { default as LinkedInIcon } from './LINKEDIN_ICON.svg'
export { default as TeamIcon } from './TEAM_ICON.svg'
export { default as PortfolioIcon } from './PORTFOLIO_ICON.svg'
